### ISSUE TITLE
Make and add a favicon 

### ISSUE THREAD

**Issue by WinstonPais** [WinstonPais/itadakimasu#3]
help to add favicon:
https://stackoverflow.com/questions/4888377/how-to-add-a-browser-tab-icon-favicon-for-a-website

@vinstenleon add the image to be used.

**Comment by vinstenleon** [comment]
![favicon](https://user-images.githubusercontent.com/64498746/103200849-6e155f00-4914-11eb-90cf-708df28aad79.png)

**Comment by vinstenleon** [comment]
![logo](https://user-images.githubusercontent.com/64498746/103200939-b03ea080-4914-11eb-8e11-94d2ae15eff1.png)
